/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val javafxPlatform = when {
    org.gradle.internal.os.OperatingSystem.current().isWindows -> "win"
    org.gradle.internal.os.OperatingSystem.current().isMacOsX -> "mac"
    org.gradle.internal.os.OperatingSystem.current().isLinux -> "linux"
    else -> throw GradleException("Unsupported operating system for JavaFX")
}

dependencies {
    // Use Scala 3 library
    implementation(libs.scala.library)

    // Cats for functional programming constructs
    implementation(libs.cats.core)
    implementation(libs.cats.effect)
    implementation(libs.fs2.core)

    // ScalaFX for GUI components
    implementation(libs.scalafx)
    implementation(variantOf(libs.javafx.base) { classifier(javafxPlatform) })
    implementation(variantOf(libs.javafx.graphics) { classifier(javafxPlatform) })
    implementation(variantOf(libs.javafx.controls) { classifier(javafxPlatform) })
    implementation(variantOf(libs.javafx.media) { classifier(javafxPlatform) })

    // This dependency is used by the application.
    implementation(libs.guava)

    // Use Scalatest for testing our library
    testImplementation(libs.junit)
    testImplementation(libs.scalatest)
    testImplementation(libs.junit.v4.v13.v2.v13)

    // Need scala-xml at test runtime
    testRuntimeOnly(libs.scala.xml)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.gridsim.gui.app.GuiApp"
}

tasks.jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.register("ciAssemble") {
    group = "build"
    description = "CI assemble"
    dependsOn("assemble")
}

tasks.register("ciBuild") {
    group = "build"
    description = "CI build without added checks"
    dependsOn("assemble", "test")
}
